### ISSUE TITLE
RELOG Case Builder

### ISSUE THREAD

**Issue by macmribo** [ANL-CEEESA/RELOG#2]
Hello!

I am trying to run the simulation from the paper ["A systematic analysis of the costs and environmental impacts of critical materials recovery from hybrid electric vehicle batteries in the U.S"](https://www.sciencedirect.com/science/article/pii/S2589004222011026) by Iloeje et al. and I am having problems finding the **RELOG Case Builder Web Interface**. I have read the documentation and the STAR methods documents with no success. How can I access this tool?

Thank you!

**Comment by shirubana** [comment]
relog.axavier.org/casebuilder I think
